## medium type constants
I_MEDIUM = "I"
VTI_MEDIUM = "VTI"
HTI_MEDIUM = "HTI"

MEDIUM_TYPES = [I_MEDIUM, VTI_MEDIUM, HTI_MEDIUM]

## boundary type constants
SOLID_BOUNDARY = "SOLID"
ATTEN_BOUNDARY = "ATTEN"

BOUNDARY_TYPES = [SOLID_BOUNDARY, ATTEN_BOUNDARY]